post_install() {
post_upgrade
}

post_upgrade() {
    if grep -q "Beryllium-multilib" /etc/pacman.conf; then
        echo "Beryllium-multilib repo is already in pacman.conf"
    else
        echo "Beryllium-multilib repo is not in pacman.conf"
        cp /etc/pacman.conf /etc/pacman.conf.bak
        sed -i '/\[Beryllium\]/i [Beryllium-multilib]\nInclude = /etc/pacman.d/beryllium-mirrorlist\n' /etc/pacman.conf
    fi
}
